development:
  adapter: postgresql
  encoding: utf8
  database: secretsanta_development
  username: ambhalla
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: secretsanta_test
  username: ambhalla
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: secretsanta_production
  username: ambhalla
  password:
  host: localhost
